"""Add Slack and Summary fields

Revision ID: 8cbcbbbc7948
Revises: e4f5cb72a68f
Create Date: 2024-07-24 15:55:08.974070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cbcbbbc7948'
down_revision: Union[str, None] = 'e4f5cb72a68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False, default={}),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('slack_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('slack_installation_settings', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'users', ['slack_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'slack_installation_settings')
    op.drop_column('users', 'slack_user_id')
    op.drop_table('summaries')
    # ### end Alembic commands ###
